// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cart-service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddCartRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Cart                 *Cart    `protobuf:"bytes,2,opt,name=cart,proto3" json:"cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCartRequest) Reset()         { *m = AddCartRequest{} }
func (m *AddCartRequest) String() string { return proto.CompactTextString(m) }
func (*AddCartRequest) ProtoMessage()    {}
func (*AddCartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f239c711bf927c84, []int{0}
}

func (m *AddCartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCartRequest.Unmarshal(m, b)
}
func (m *AddCartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCartRequest.Marshal(b, m, deterministic)
}
func (m *AddCartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCartRequest.Merge(m, src)
}
func (m *AddCartRequest) XXX_Size() int {
	return xxx_messageInfo_AddCartRequest.Size(m)
}
func (m *AddCartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCartRequest proto.InternalMessageInfo

func (m *AddCartRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *AddCartRequest) GetCart() *Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

type Response struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f239c711bf927c84, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AddCartRequest)(nil), "proto.AddCartRequest")
	proto.RegisterType((*Response)(nil), "proto.Response")
}

func init() { proto.RegisterFile("cart-service.proto", fileDescriptor_f239c711bf927c84) }

var fileDescriptor_f239c711bf927c84 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0x2f, 0xa2, 0x97, 0x73, 0x02, 0x27, 0x0c, 0x28, 0xe1, 0x1a, 0x65, 0x2b, 0x05, 0xbd,
	0xe2, 0xd2, 0xda, 0x88, 0x85, 0x8d, 0xd5, 0x8a, 0x3f, 0x60, 0x4d, 0x06, 0x49, 0x11, 0x37, 0xee,
	0x4c, 0xf2, 0x67, 0xfc, 0xb3, 0xb2, 0x93, 0x8d, 0x9a, 0xc2, 0x6a, 0x99, 0xf7, 0xde, 0x7e, 0xf3,
	0x06, 0xb0, 0x76, 0x41, 0xee, 0x98, 0xc2, 0xd8, 0xd6, 0xb4, 0xef, 0x83, 0x17, 0x8f, 0x27, 0xfa,
	0xec, 0xb6, 0x1d, 0x31, 0xbb, 0x77, 0xe2, 0x49, 0x36, 0x16, 0xb6, 0x0f, 0x4d, 0xf3, 0xe8, 0x82,
	0x58, 0xfa, 0x1c, 0x88, 0x05, 0x2f, 0xe1, 0x78, 0x60, 0x0a, 0x65, 0x76, 0x95, 0x5d, 0x17, 0x87,
	0x62, 0xca, 0xed, 0x5f, 0x99, 0x82, 0x55, 0x23, 0x06, 0x22, 0xbf, 0x3c, 0x5a, 0x04, 0x14, 0xa1,
	0x86, 0xb9, 0x87, 0x8d, 0x25, 0xee, 0xfd, 0x07, 0x13, 0x5e, 0xc0, 0x9a, 0xc5, 0xc9, 0xc0, 0xca,
	0xdb, 0xd8, 0x34, 0x61, 0x09, 0x79, 0x6a, 0xa2, 0x9c, 0x53, 0x3b, 0x8f, 0x87, 0xaf, 0x0c, 0x8a,
	0x08, 0x7b, 0x99, 0xea, 0x63, 0x05, 0x79, 0x6a, 0x88, 0xe7, 0x69, 0xd7, 0xb2, 0xf1, 0xee, 0x2c,
	0xc9, 0xf3, 0x52, 0xb3, 0xc2, 0x1b, 0xc8, 0x9f, 0x48, 0xf4, 0xd3, 0xdf, 0x0b, 0x7e, 0xa2, 0xd1,
	0x79, 0x6e, 0x59, 0xcc, 0x0a, 0x6f, 0x01, 0x2c, 0x75, 0x7e, 0xa4, 0xff, 0xd3, 0xbf, 0xe0, 0xb7,
	0xb5, 0x2a, 0xd5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x64, 0x83, 0x52, 0xe7, 0x63, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CartServiceClient is the client API for CartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CartServiceClient interface {
	AddCart(ctx context.Context, in *AddCartRequest, opts ...grpc.CallOption) (*Response, error)
	GetCart(ctx context.Context, in *User, opts ...grpc.CallOption) (*CartList, error)
	RemoveCart(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error)
}

type cartServiceClient struct {
	cc *grpc.ClientConn
}

func NewCartServiceClient(cc *grpc.ClientConn) CartServiceClient {
	return &cartServiceClient{cc}
}

func (c *cartServiceClient) AddCart(ctx context.Context, in *AddCartRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.CartService/AddCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) GetCart(ctx context.Context, in *User, opts ...grpc.CallOption) (*CartList, error) {
	out := new(CartList)
	err := c.cc.Invoke(ctx, "/proto.CartService/GetCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) RemoveCart(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.CartService/RemoveCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartServiceServer is the server API for CartService service.
type CartServiceServer interface {
	AddCart(context.Context, *AddCartRequest) (*Response, error)
	GetCart(context.Context, *User) (*CartList, error)
	RemoveCart(context.Context, *User) (*Response, error)
}

// UnimplementedCartServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCartServiceServer struct {
}

func (*UnimplementedCartServiceServer) AddCart(ctx context.Context, req *AddCartRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCart not implemented")
}
func (*UnimplementedCartServiceServer) GetCart(ctx context.Context, req *User) (*CartList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCart not implemented")
}
func (*UnimplementedCartServiceServer) RemoveCart(ctx context.Context, req *User) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCart not implemented")
}

func RegisterCartServiceServer(s *grpc.Server, srv CartServiceServer) {
	s.RegisterService(&_CartService_serviceDesc, srv)
}

func _CartService_AddCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).AddCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CartService/AddCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).AddCart(ctx, req.(*AddCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_GetCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).GetCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CartService/GetCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).GetCart(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_RemoveCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).RemoveCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CartService/RemoveCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).RemoveCart(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _CartService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CartService",
	HandlerType: (*CartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCart",
			Handler:    _CartService_AddCart_Handler,
		},
		{
			MethodName: "GetCart",
			Handler:    _CartService_GetCart_Handler,
		},
		{
			MethodName: "RemoveCart",
			Handler:    _CartService_RemoveCart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cart-service.proto",
}
