// Code generated by protoc-gen-go. DO NOT EDIT.
// source: checkout-service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckoutResponse struct {
	Status               bool          `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Cart                 []*Cart       `protobuf:"bytes,3,rep,name=cart,proto3" json:"cart,omitempty"`
	Shipping             *ShippingCost `protobuf:"bytes,4,opt,name=shipping,proto3" json:"shipping,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CheckoutResponse) Reset()         { *m = CheckoutResponse{} }
func (m *CheckoutResponse) String() string { return proto.CompactTextString(m) }
func (*CheckoutResponse) ProtoMessage()    {}
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba002af7914fecb4, []int{0}
}

func (m *CheckoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutResponse.Unmarshal(m, b)
}
func (m *CheckoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutResponse.Marshal(b, m, deterministic)
}
func (m *CheckoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutResponse.Merge(m, src)
}
func (m *CheckoutResponse) XXX_Size() int {
	return xxx_messageInfo_CheckoutResponse.Size(m)
}
func (m *CheckoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutResponse proto.InternalMessageInfo

func (m *CheckoutResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *CheckoutResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CheckoutResponse) GetCart() []*Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

func (m *CheckoutResponse) GetShipping() *ShippingCost {
	if m != nil {
		return m.Shipping
	}
	return nil
}

type ShippingCostList struct {
	ShippingCost         *ShippingCost `protobuf:"bytes,1,opt,name=shippingCost,proto3" json:"shippingCost,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ShippingCostList) Reset()         { *m = ShippingCostList{} }
func (m *ShippingCostList) String() string { return proto.CompactTextString(m) }
func (*ShippingCostList) ProtoMessage()    {}
func (*ShippingCostList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba002af7914fecb4, []int{1}
}

func (m *ShippingCostList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShippingCostList.Unmarshal(m, b)
}
func (m *ShippingCostList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShippingCostList.Marshal(b, m, deterministic)
}
func (m *ShippingCostList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShippingCostList.Merge(m, src)
}
func (m *ShippingCostList) XXX_Size() int {
	return xxx_messageInfo_ShippingCostList.Size(m)
}
func (m *ShippingCostList) XXX_DiscardUnknown() {
	xxx_messageInfo_ShippingCostList.DiscardUnknown(m)
}

var xxx_messageInfo_ShippingCostList proto.InternalMessageInfo

func (m *ShippingCostList) GetShippingCost() *ShippingCost {
	if m != nil {
		return m.ShippingCost
	}
	return nil
}

type ShippingCost struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShippingCost) Reset()         { *m = ShippingCost{} }
func (m *ShippingCost) String() string { return proto.CompactTextString(m) }
func (*ShippingCost) ProtoMessage()    {}
func (*ShippingCost) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba002af7914fecb4, []int{2}
}

func (m *ShippingCost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShippingCost.Unmarshal(m, b)
}
func (m *ShippingCost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShippingCost.Marshal(b, m, deterministic)
}
func (m *ShippingCost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShippingCost.Merge(m, src)
}
func (m *ShippingCost) XXX_Size() int {
	return xxx_messageInfo_ShippingCost.Size(m)
}
func (m *ShippingCost) XXX_DiscardUnknown() {
	xxx_messageInfo_ShippingCost.DiscardUnknown(m)
}

var xxx_messageInfo_ShippingCost proto.InternalMessageInfo

func (m *ShippingCost) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ShippingCost) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ShippingCost) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func init() {
	proto.RegisterType((*CheckoutResponse)(nil), "proto.CheckoutResponse")
	proto.RegisterType((*ShippingCostList)(nil), "proto.ShippingCostList")
	proto.RegisterType((*ShippingCost)(nil), "proto.ShippingCost")
}

func init() { proto.RegisterFile("checkout-service.proto", fileDescriptor_ba002af7914fecb4) }

var fileDescriptor_ba002af7914fecb4 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xcd, 0x4e, 0xf2, 0x50,
	0x10, 0xe5, 0xf2, 0xf7, 0xc1, 0x40, 0x80, 0xcc, 0x67, 0xb0, 0xc1, 0x85, 0x4d, 0x57, 0xdd, 0x58,
	0x92, 0xba, 0xf0, 0x01, 0xd0, 0x68, 0xa2, 0xab, 0x4b, 0x7c, 0x80, 0xd2, 0x0c, 0xa5, 0x51, 0xb8,
	0xcd, 0x9d, 0xc1, 0xc4, 0x67, 0x70, 0xef, 0xf3, 0x1a, 0x6f, 0x5b, 0x02, 0x24, 0xae, 0xda, 0x33,
	0xe7, 0xdc, 0x93, 0x99, 0x73, 0x60, 0x9a, 0x6e, 0x28, 0x7d, 0x33, 0x7b, 0xb9, 0x61, 0xb2, 0x1f,
	0x79, 0x4a, 0x51, 0x61, 0x8d, 0x18, 0xec, 0xb8, 0xcf, 0xec, 0x2a, 0x33, 0x26, 0x7b, 0xa7, 0xb9,
	0x43, 0xab, 0xfd, 0x7a, 0x4e, 0xdb, 0x42, 0x3e, 0x4b, 0xcd, 0x6c, 0xb4, 0x25, 0xe6, 0x24, 0x23,
	0x2e, 0x71, 0xf0, 0xad, 0x60, 0xb2, 0xa8, 0xec, 0x34, 0x71, 0x61, 0x76, 0x4c, 0x38, 0x85, 0x2e,
	0x4b, 0x22, 0x7b, 0xf6, 0x94, 0xaf, 0xc2, 0x9e, 0xae, 0x10, 0x7a, 0xf0, 0xaf, 0x7a, 0xee, 0x35,
	0x7d, 0x15, 0xf6, 0x75, 0x0d, 0xf1, 0x1a, 0xda, 0x69, 0x62, 0xc5, 0x6b, 0xf9, 0xad, 0x70, 0x10,
	0x0f, 0x4a, 0xf3, 0x68, 0x91, 0x58, 0xd1, 0x8e, 0xc0, 0x39, 0xf4, 0x78, 0x93, 0x17, 0x45, 0xbe,
	0xcb, 0xbc, 0xb6, 0xaf, 0xc2, 0x41, 0xfc, 0xbf, 0x12, 0x2d, 0xab, 0xf1, 0xc2, 0xb0, 0xe8, 0x83,
	0x28, 0x78, 0x86, 0xc9, 0x31, 0xf3, 0x92, 0xb3, 0xe0, 0x1d, 0x0c, 0xf9, 0x68, 0xe6, 0xb6, 0xfb,
	0xc3, 0xe8, 0x44, 0x18, 0x3c, 0xc1, 0xf0, 0x98, 0x45, 0x84, 0xf6, 0xda, 0x9a, 0xad, 0x33, 0xe8,
	0x6b, 0xf7, 0x8f, 0x23, 0x68, 0x8a, 0xa9, 0xee, 0x6a, 0x8a, 0xc1, 0x0b, 0xe8, 0x14, 0x36, 0x4f,
	0xc9, 0x6b, 0xf9, 0x2a, 0xec, 0xe8, 0x12, 0xc4, 0x5f, 0x0a, 0xc6, 0x75, 0x5e, 0xcb, 0x32, 0x7d,
	0x8c, 0xa1, 0x57, 0x8f, 0xb0, 0x3e, 0xfd, 0x95, 0xc9, 0xce, 0x2e, 0xeb, 0x1c, 0xce, 0x02, 0x0e,
	0x1a, 0x78, 0x0f, 0xe3, 0x47, 0x92, 0x93, 0xa5, 0xa6, 0x51, 0x59, 0x5c, 0x54, 0x17, 0x17, 0x3d,
	0xfc, 0x16, 0x77, 0x70, 0x39, 0x8f, 0x23, 0x68, 0xac, 0xba, 0x8e, 0xb9, 0xfd, 0x09, 0x00, 0x00,
	0xff, 0xff, 0x70, 0x7c, 0xaf, 0x5f, 0x12, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CheckoutServiceClient is the client API for CheckoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CheckoutServiceClient interface {
	Checkout(ctx context.Context, in *User, opts ...grpc.CallOption) (*CheckoutResponse, error)
	GetShippingCost(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ShippingCostList, error)
}

type checkoutServiceClient struct {
	cc *grpc.ClientConn
}

func NewCheckoutServiceClient(cc *grpc.ClientConn) CheckoutServiceClient {
	return &checkoutServiceClient{cc}
}

func (c *checkoutServiceClient) Checkout(ctx context.Context, in *User, opts ...grpc.CallOption) (*CheckoutResponse, error) {
	out := new(CheckoutResponse)
	err := c.cc.Invoke(ctx, "/proto.CheckoutService/Checkout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) GetShippingCost(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ShippingCostList, error) {
	out := new(ShippingCostList)
	err := c.cc.Invoke(ctx, "/proto.CheckoutService/GetShippingCost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckoutServiceServer is the server API for CheckoutService service.
type CheckoutServiceServer interface {
	Checkout(context.Context, *User) (*CheckoutResponse, error)
	GetShippingCost(context.Context, *empty.Empty) (*ShippingCostList, error)
}

// UnimplementedCheckoutServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCheckoutServiceServer struct {
}

func (*UnimplementedCheckoutServiceServer) Checkout(ctx context.Context, req *User) (*CheckoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkout not implemented")
}
func (*UnimplementedCheckoutServiceServer) GetShippingCost(ctx context.Context, req *empty.Empty) (*ShippingCostList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShippingCost not implemented")
}

func RegisterCheckoutServiceServer(s *grpc.Server, srv CheckoutServiceServer) {
	s.RegisterService(&_CheckoutService_serviceDesc, srv)
}

func _CheckoutService_Checkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).Checkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CheckoutService/Checkout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).Checkout(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_GetShippingCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).GetShippingCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CheckoutService/GetShippingCost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).GetShippingCost(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _CheckoutService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CheckoutService",
	HandlerType: (*CheckoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Checkout",
			Handler:    _CheckoutService_Checkout_Handler,
		},
		{
			MethodName: "GetShippingCost",
			Handler:    _CheckoutService_GetShippingCost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "checkout-service.proto",
}
