// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Cart struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Qty                  int32    `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cart) Reset()         { *m = Cart{} }
func (m *Cart) String() string { return proto.CompactTextString(m) }
func (*Cart) ProtoMessage()    {}
func (*Cart) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *Cart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cart.Unmarshal(m, b)
}
func (m *Cart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cart.Marshal(b, m, deterministic)
}
func (m *Cart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cart.Merge(m, src)
}
func (m *Cart) XXX_Size() int {
	return xxx_messageInfo_Cart.Size(m)
}
func (m *Cart) XXX_DiscardUnknown() {
	xxx_messageInfo_Cart.DiscardUnknown(m)
}

var xxx_messageInfo_Cart proto.InternalMessageInfo

func (m *Cart) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cart) GetQty() int32 {
	if m != nil {
		return m.Qty
	}
	return 0
}

type CartList struct {
	Cart                 []*Cart  `protobuf:"bytes,1,rep,name=cart,proto3" json:"cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CartList) Reset()         { *m = CartList{} }
func (m *CartList) String() string { return proto.CompactTextString(m) }
func (*CartList) ProtoMessage()    {}
func (*CartList) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *CartList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartList.Unmarshal(m, b)
}
func (m *CartList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartList.Marshal(b, m, deterministic)
}
func (m *CartList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartList.Merge(m, src)
}
func (m *CartList) XXX_Size() int {
	return xxx_messageInfo_CartList.Size(m)
}
func (m *CartList) XXX_DiscardUnknown() {
	xxx_messageInfo_CartList.DiscardUnknown(m)
}

var xxx_messageInfo_CartList proto.InternalMessageInfo

func (m *CartList) GetCart() []*Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*Cart)(nil), "proto.Cart")
	proto.RegisterType((*CartList)(nil), "proto.CartList")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x62,
	0x5c, 0x2c, 0xa1, 0xc5, 0xa9, 0x45, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0xac, 0x41, 0x4c, 0x99, 0x29, 0x4a, 0x3a, 0x5c, 0x2c, 0xce, 0x89, 0x45, 0x25, 0x42, 0x42,
	0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x60, 0x19, 0xce, 0x20, 0x30, 0x5b, 0x48, 0x80, 0x8b, 0xb9,
	0xb0, 0xa4, 0x52, 0x82, 0x09, 0xac, 0x18, 0xc4, 0x54, 0xd2, 0xe6, 0xe2, 0x00, 0xa9, 0xf6, 0xc9,
	0x2c, 0x2e, 0x11, 0x92, 0xe7, 0x62, 0x49, 0x4e, 0x2c, 0x2a, 0x91, 0x60, 0x54, 0x60, 0xd6, 0xe0,
	0x36, 0xe2, 0x86, 0x58, 0xa7, 0x07, 0x92, 0x0e, 0x02, 0x4b, 0x24, 0xb1, 0x81, 0x45, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x28, 0xf1, 0xd1, 0x34, 0x92, 0x00, 0x00, 0x00,
}
