# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import cart_service_pb2 as cart__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class CartServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddCart = channel.unary_unary(
        '/proto.CartService/AddCart',
        request_serializer=cart__service__pb2.Cart.SerializeToString,
        response_deserializer=cart__service__pb2.Response.FromString,
        )
    self.GetCart = channel.unary_unary(
        '/proto.CartService/GetCart',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=cart__service__pb2.Cart.FromString,
        )


class CartServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddCart(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCart(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CartServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddCart': grpc.unary_unary_rpc_method_handler(
          servicer.AddCart,
          request_deserializer=cart__service__pb2.Cart.FromString,
          response_serializer=cart__service__pb2.Response.SerializeToString,
      ),
      'GetCart': grpc.unary_unary_rpc_method_handler(
          servicer.GetCart,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=cart__service__pb2.Cart.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.CartService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
