# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cart-service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import messages_pb2 as messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cart-service.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x63\x61rt-service.proto\x12\x05proto\x1a\x0emessages.proto\"F\n\x0e\x41\x64\x64\x43\x61rtRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.proto.User\x12\x19\n\x04\x63\x61rt\x18\x02 \x01(\x0b\x32\x0b.proto.Cart\"+\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9b\x01\n\x0b\x43\x61rtService\x12\x33\n\x07\x41\x64\x64\x43\x61rt\x12\x15.proto.AddCartRequest\x1a\x0f.proto.Response\"\x00\x12)\n\x07GetCart\x12\x0b.proto.User\x1a\x0f.proto.CartList\"\x00\x12,\n\nRemoveCart\x12\x0b.proto.User\x1a\x0f.proto.Response\"\x00\x62\x06proto3')
  ,
  dependencies=[messages__pb2.DESCRIPTOR,])




_ADDCARTREQUEST = _descriptor.Descriptor(
  name='AddCartRequest',
  full_name='proto.AddCartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='proto.AddCartRequest.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cart', full_name='proto.AddCartRequest.cart', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=115,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='proto.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='proto.Response.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=160,
)

_ADDCARTREQUEST.fields_by_name['user'].message_type = messages__pb2._USER
_ADDCARTREQUEST.fields_by_name['cart'].message_type = messages__pb2._CART
DESCRIPTOR.message_types_by_name['AddCartRequest'] = _ADDCARTREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddCartRequest = _reflection.GeneratedProtocolMessageType('AddCartRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDCARTREQUEST,
  '__module__' : 'cart_service_pb2'
  # @@protoc_insertion_point(class_scope:proto.AddCartRequest)
  })
_sym_db.RegisterMessage(AddCartRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'cart_service_pb2'
  # @@protoc_insertion_point(class_scope:proto.Response)
  })
_sym_db.RegisterMessage(Response)



_CARTSERVICE = _descriptor.ServiceDescriptor(
  name='CartService',
  full_name='proto.CartService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=163,
  serialized_end=318,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddCart',
    full_name='proto.CartService.AddCart',
    index=0,
    containing_service=None,
    input_type=_ADDCARTREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCart',
    full_name='proto.CartService.GetCart',
    index=1,
    containing_service=None,
    input_type=messages__pb2._USER,
    output_type=messages__pb2._CARTLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveCart',
    full_name='proto.CartService.RemoveCart',
    index=2,
    containing_service=None,
    input_type=messages__pb2._USER,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CARTSERVICE)

DESCRIPTOR.services_by_name['CartService'] = _CARTSERVICE

# @@protoc_insertion_point(module_scope)
