# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import services_pb2 as services__pb2


class ProductServiceStub(object):
  """-------------- Product Service --------------

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetProductById = channel.unary_unary(
        '/proto.ProductService/GetProductById',
        request_serializer=services__pb2.ProductRequest.SerializeToString,
        response_deserializer=services__pb2.Product.FromString,
        )
    self.GetProduct = channel.unary_unary(
        '/proto.ProductService/GetProduct',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=services__pb2.ProductList.FromString,
        )


class ProductServiceServicer(object):
  """-------------- Product Service --------------

  """

  def GetProductById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetProduct(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetProductById': grpc.unary_unary_rpc_method_handler(
          servicer.GetProductById,
          request_deserializer=services__pb2.ProductRequest.FromString,
          response_serializer=services__pb2.Product.SerializeToString,
      ),
      'GetProduct': grpc.unary_unary_rpc_method_handler(
          servicer.GetProduct,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=services__pb2.ProductList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.ProductService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class CartServiceStub(object):
  """-------------- Cart Service --------------

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddCart = channel.unary_unary(
        '/proto.CartService/AddCart',
        request_serializer=services__pb2.AddCartRequest.SerializeToString,
        response_deserializer=services__pb2.Response.FromString,
        )
    self.GetCart = channel.unary_unary(
        '/proto.CartService/GetCart',
        request_serializer=services__pb2.User.SerializeToString,
        response_deserializer=services__pb2.CartList.FromString,
        )
    self.RemoveCart = channel.unary_unary(
        '/proto.CartService/RemoveCart',
        request_serializer=services__pb2.User.SerializeToString,
        response_deserializer=services__pb2.Response.FromString,
        )


class CartServiceServicer(object):
  """-------------- Cart Service --------------

  """

  def AddCart(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCart(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveCart(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CartServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddCart': grpc.unary_unary_rpc_method_handler(
          servicer.AddCart,
          request_deserializer=services__pb2.AddCartRequest.FromString,
          response_serializer=services__pb2.Response.SerializeToString,
      ),
      'GetCart': grpc.unary_unary_rpc_method_handler(
          servicer.GetCart,
          request_deserializer=services__pb2.User.FromString,
          response_serializer=services__pb2.CartList.SerializeToString,
      ),
      'RemoveCart': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveCart,
          request_deserializer=services__pb2.User.FromString,
          response_serializer=services__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.CartService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class CheckoutServiceStub(object):
  """-------------- Checkout Service --------------

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Checkout = channel.unary_unary(
        '/proto.CheckoutService/Checkout',
        request_serializer=services__pb2.User.SerializeToString,
        response_deserializer=services__pb2.CheckoutResponse.FromString,
        )
    self.GetShippingCost = channel.unary_unary(
        '/proto.CheckoutService/GetShippingCost',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=services__pb2.ShippingCostList.FromString,
        )


class CheckoutServiceServicer(object):
  """-------------- Checkout Service --------------

  """

  def Checkout(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetShippingCost(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CheckoutServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Checkout': grpc.unary_unary_rpc_method_handler(
          servicer.Checkout,
          request_deserializer=services__pb2.User.FromString,
          response_serializer=services__pb2.CheckoutResponse.SerializeToString,
      ),
      'GetShippingCost': grpc.unary_unary_rpc_method_handler(
          servicer.GetShippingCost,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=services__pb2.ShippingCostList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.CheckoutService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
